server:
  port: 8080

spring:
  profiles:
    active: dev

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info
small:
  wechat:
    appid: ${small.wechat.appid}
    secret: ${small.wechat.secret}
